### Photo Upload
POST http://localhost:3000/photo/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="photo.jpg"
Content-Type: image/jpeg

< ./A7C04877.jpg
--WebAppBoundary--

### List all photos
GET http://localhost:3000/photo

### Photo image by id
GET http://localhost:3000/photo/bad69006-c3a6-4b35-befe-b25e40e9eea8
